### ISSUE TITLE
Platform error cannot import SUPPORT_AWAY_MODE

### ISSUE THREAD

**Issue by artmg** [alex-0103/warmup4IE#7]
When trying out this repo on HomeAssistant version 102.3 I get the error

`Platform error: climate - ImportError: cannot import name 'SUPPORT_AWAY_MODE' from 'homeassistant.components.climate.const'`

and the full trace is:

```
2019-12-05 15:04:40 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for warmup_cc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-05 15:04:40 ERROR (MainThread) [homeassistant.config] Platform error: climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 762, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 232, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/warmup_cc/climate.py", line 12, in <module>
    from homeassistant.components.climate.const import (
ImportError: cannot import name 'SUPPORT_AWAY_MODE' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)
```

**Comment by artmg** [comment]
I have retried with the latest development branch/fork `git clone --single-branch --branch dev https://github.com/foxy82/warmup4IE.git /tmp/warmup4IE` and this issue no longer occurs. 

As soon as PR #8 is merged this issue should go away. Many thanks to @foxy82 for the development and to @alex-0103 for maintaining this code
